
# Lets you enable / disable certain features and modify them.
[features]
	# (Default = true) Optimizes vanilla's per-player mobspawning by using PaperMC's PlayerMobDistanceMap.
	use_distance_map = true
	# (Default = false) Stops the server from loading spawn chunks.
	disable_spawn_chunks = false
	# (Default = false) Allows more xp orbs to merge with one another, to reduce xp orb lag.
	fast_xp_merging = true
	# (Default = false) Prevents players from moving into unloaded chunks.
	prevent_moving_into_unloaded_chunks = true
	# (Default = true) Whether the custom portal radius will use the vanilla dimension scale.
	portal_search_vanilla_scaling = true
	# (Default = 128) The radius at which the game will look for other portals. Lower values can reduce lagspikes.
	portal_search_radius = 128
	# (Default = 16) The radius at which the game will try to create new portals.
	# It is recommended to make this smaller than the search radius.
	portal_create_radius = 16
	# (Default = false) Makes villagers tick less often if they are stuck in a 1x1 space.
	lobotomize_villagers = true
	# (Default = 20) Decides the interval in between villager ticks when lobotomized.
	lobotomized_tick_interval = 20
	# (Default = -1) The threshold MSPT that the server is allowed to run mid-tick chunk saves at.
	# Setting this value to negative will disable this feature.
	chunk_save_threshold = -1
	# (Default = 5) The amount of minutes in between auto-save intervals when /save-on is active.
	auto_save_interval = 5
	# (Default = 0.5) Decides the radius in blocks that items / xp will merge at.
	item_merge_radius = 2.0
	xp_merge_radius = 4.0

# Modifies mobcaps, no-chunk-tick, simulation and view-distance depending on the MSPT.
[dynamic]
	# (Default = false) Enables this feature.
	enabled = true
	# (Default = 35) The average MSPT to target.
	target_mspt = 35
	# (Default = 15) The amount of seconds between dynamic performance updates.
	update_rate = 15
	# (Default = 150) The amount of seconds between dynamic viewdistance updates.
	# This value is separate from the other checks because it makes all clients reload their chunks.
	view_distance_update_rate = 150
	# (Default = [Max: 10, Min: 2]) Distance in which random ticks and mobspawning can happen.
	max_chunk_tick_distance = 14
	min_chunk_tick_distance = 8
	# (Default = [Max: 10, Min: 2]) Distance in which the world will tick, similar to no-tick-vd.
	max_simulation_distance = 10
	min_simulation_distance = 4
	# (Default = [Max: 10, Min: 2]) Distance in which the world will render.
	max_view_distance = 12
	min_view_distance = 6
	# (Default = [Max: 1.0, Min: 0.3]) Global multiplier that decides the percentage of the mobcap to be used.
	max_mobcap = 1.0
	min_mobcap = 0.3

# Stops animals / villagers from breeding if there are too many of the same type nearby.
[entity_limits]
	# (Default = false) Enables this feature.
	enabled = false
	# (Default = [Villager: 24, Animals: 32]) Maximum count before stopping entities of the same type from breeding.
	villager_count = 24
	animal_count = 32
	# (Default = [Villager: 64, Animals: 64]) The range it will check for entities of the same type.
	villager_range = 64
	animal_range = 64

# Allows you to disable specific commands and modify the way some of them are formatted.
[commands]
	# Enables / disables the /sc status command.
	command_status = true
	# The content for the /sc status command.
	status_content = "§3>----( §bServerCore §3)----<\n§7>§8> §3Chunk-Tick Distance: §a%CHUNK_TICK_DISTANCE%\n§7>§8> §3Simulation Distance: §a%SIMULATION_DISTANCE%\n§7>§8> §3View Distance: §a%VIEW_DISTANCE%\n§7>§8> §3Mobcap Multiplier: §a%MOBCAPS%"
	# Enables / disables the /mobcaps command.
	command_mobcaps = true
	# The title for the /mobcaps command.
	mobcap_title = "§3Per Player Mobcaps (§a%MODIFIER%§3)"
	# The content for the /mobcaps command. This is displayed for every existing spawngroup.
	mobcap_content = "§8- §3%NAME%: §a%CURRENT% §8/ §a%CAPACITY%"

# Stops entities from ticking if they are too far away.
[activation_range]
	# (Default = false) Enables this feature.
	enabled = true
	# (Default = false) Enables vertical range checks. By default, activation ranges only work horizontally.
	# This can greatly improve performance on taller worlds, but might break a few very specific ai-based mobfarms.
	use_vertical_range = false
	# (Default = true) Allows villagers to tick regardless of the activation range when panicking.
	villager_tick_panic = true
	# (Default = false) Allows villagers to tick regardless of the activation range.
	villager_tick_always = false
	# (Default = 20) The time in seconds that a villager needs to be inactive for before obtaining work immunity (if it has work tasks).
	villager_work_immunity_after = 20
	# (Default = 20) The amount of ticks an inactive villager will wake up for when it has work immunity.
	villager_work_immunity_for = 20
	# Activation Range = The range an entity is required to be in from a player to tick.
	# Tick Inactive = Whether an entity is allowed to tick once per second whilst inactive.
	# Wakeup Max = The maximum amount of entities in the same group and world that are allowed to be awakened at the same time.
	# Wakeup Interval = The interval between inactive entity wake ups in seconds.
	# Activation range settings for villagers.
	villager_activation_range = 16
	villager_tick_inactive = false
	villager_wakeup_max = 4
	villager_wakeup_interval = 30
	# Activation range settings for monsters.
	monster_activation_range = 32
	monster_tick_inactive = false
	monster_wakeup_max = 8
	monster_wakeup_interval = 20
	# Activation range settings for animals.
	animal_activation_range = 16
	animal_tick_inactive = false
	animal_wakeup_max = 4
	animal_wakeup_interval = 60
	# Activation range settings for flying mobs.
	flying_activation_range = 48
	flying_wakeup_max = 8
	flying_wakeup_interval = 10
	flying_tick_inactive = false
	# Activation range settings for water mobs.
	water_activation_range = 16
	water_tick_inactive = true
	# Activation range settings for neutral mobs.
	neutral_activation_range = 24
	neutral_tick_inactive = false
	# Activation range settings for zombies.
	zombie_activation_range = 16
	zombie_tick_inactive = false
	# Activation range settings for raider mobs.
	raider_activation_range = 48
	raider_tick_inactive = false
	# Activation range settings for miscellaneous entities.
	misc_activation_range = 16
	misc_tick_inactive = false

