# These are supported funding model platforms

patreon: simpearth
open_collective: srnyx
ko_fi: srnyx
community_bridge: srnyx
liberapay: srnyx
issuehunt: srnyx
otechie: srnyx
custom: ['https://srnyx.xyz/donate']
