# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: simpearth
open_collective: # Replace with a single Open Collective username
ko_fi: srnyx
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: srnyx
otechie: # Replace with a single Otechie username
custom: ['https://srnyx.xyz/donate']
bmac: srnyx
