name: Fabric 1.16.x Builds

on:
  push:
    branches: [ master ]
    paths:
      - 'Fabric/1.16.*/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'Fabric 1.16.5/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Fabric 1.16.x
        path: "Fabric/1.16.*"
