name: Fabric 1.16.5 Builds

on:
  push:
    branches: [ main ]
    paths:
      - 'Fabric 1.16.5/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Fabric 1.16.5/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p Fabric 1.16.5
    - uses: actions/upload-artifact@v2
      with:
        name: Fabric 1.16.5
        path: Fabric 1.16.5
