# This is a basic workflow to help you get started with Actions

name: Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Fabric 1.16.5
    - uses: actions/checkout@v2
    - run: mkdir -p Fabric 1.16.5
#    - run: echo hello > Fabric 1.16.5
    - uses: actions/upload-artifact@v2
      with:
        name: fabric-1.16.5
        path: Fabric 1.16.5
    # Fabric 1.17.1
    - uses: actions/checkout@v2
    - run: mkdir -p Fabric 1.17.1
#    - run: echo hello > Fabric 1.17.1
    - uses: actions/upload-artifact@v2
      with:
        name: fabric-1.17.1
        path: Fabric 1.17.1
    # Paper 1.8.8
    - uses: actions/checkout@v2
    - run: mkdir -p Paper 1.8.8
#    - run: echo hello > Paper 1.8.8
    - uses: actions/upload-artifact@v2
      with:
        name: paper-1.8.8
        path: Paper 1.16.5
    # Purpur 1.16.5
    - uses: actions/checkout@v2
    - run: mkdir -p Purpur 1.16.5
    - run: echo hello > Purpur 1.16.5
    - uses: actions/upload-artifact@v2
      with:
        name: purpur-1.16.5
        path: Purpur 1.16.5
    # Purpur 1.17.1
    - uses: actions/checkout@v2
#    - run: mkdir -p Purpur 1.17.1
    - run: echo hello > Purpur 1.17.1
    - uses: actions/upload-artifact@v2
      with:
        name: purpur-1.17.1
        path: Purpur 1.17.1
