name: Paper 1.8.8 Builds

on:
  push:
    branches: [ master ]
    paths:
      - 'Paper 1.8.8/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'Paper 1.8.8/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p Paper 1.8.8
    - uses: actions/upload-artifact@v2
      with:
        name: Paper 1.8.8
        path: Paper 1.8.8
