name: Paper 1.8.x Builds

on:
  push:
    branches: [ master ]
    paths:
      - 'Paper 1.8.*/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'Paper 1.8.8/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Paper 1.8.x
        path: Paper 1.8.*
