name: Purpur 1.16.5 Builds

on:
  push:
    branches: [ main ]
    paths:
      - 'Purpur 1.16.5/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Purpur 1.16.5/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Make directory
      run: mkdir -p Purpur 1.16.5
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Purpur 1.16.5
        path: Purpur 1.16.5
