name: Purpur 1.16.5 Builds

on:
  push:
    branches: [ main ]
    paths:
      - 'Purpur 1.16.5/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p Purpur 1.16.5
    - uses: actions/upload-artifact@v2
      with:
        name: Purpur 1.16.5
        path: Purpur 1.16.5
