name: Purpur 1.17.1 Builds

on:
  push:
    branches: [ main ]
    paths:
      - 'Purpur 1.17.1/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Purpur 1.17.1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p Purpur 1.17.1
    - uses: actions/upload-artifact@v2
      with:
        name: Purpur 1.17.1
        path: Purpur 1.17.1
