name: Purpur 1.18.x Builds

on:
  push:
    branches: [ master ]
    paths:
      - 'Purpur/1.18.*/**'
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'Purpur 1.18.1/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Purpur 1.18.x
        path: Purpur 1.18.*
